import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { AuthProvider } from "./contexts/authProvide";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-secondary ${inter.className}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
